FormatVersion: OOS-2019-06-01
Description:
  en: Creates an ECS image and updates scaling configuration image ID
  zh-cn: 创建一个新ECS镜像并更新伸缩配置中的镜像ID
  name-en: ACS-ESS-CreateImageAndUpdateScalingConfiguration
  name-zh-cn: 创建一个新ECS镜像并更新弹性伸缩配置
  categories:
    - elastic_manage
Parameters:
  instanceId:
    Label:
      en: InstanceId
      zh-cn: ECS实例ID
    Type: String
  targetImageName:
    Label:
      en: TargetImageName
      zh-cn: 镜像名称
    Description:
      en: <p class="p">Note:</p> <ul class="ul"> <li class="li">Length is 2~128 English or Chinese characters</li> <li class="li"><font color='red'>must start with big or small letters or Chinese, not http:// and https://. </font></li> <li class="li">Can contain numbers, colons (:), underscores (_), or dashes (-). </li> </ul>
      zh-cn: <p class="p">注意：</p> <ul class="ul"> <li class="li">长度为2~128个英文或中文字符</li> <li class="li"><font color='red'>必须以大小字母或中文开头，不能以http://和https://开头。</font></li> <li class="li">可以包含数字、半角冒号（:）、下划线（_）或者短划线（-）。</li> </ul>
    Type: String
    Default: CreateImage_from_{{instanceId}}
  scalingConfigurationIds:
    Label:
      en: ScalingConfigurationIds
      zh-cn: 待修改的伸缩配置ID列表
    Type: List
  tags:
    Label:
      en: ImageTag
      zh-cn: 镜像标签
    Type: Json
    AssociationProperty: Tags
    AssociationPropertyMetadata:
      ShowSystem: false
    Default: []
  OOSAssumeRole:
    Label:
      en: OOSAssumeRole
      zh-cn: OOS扮演的RAM角色
    Type: String
    Default: ''
  dataDiskCategories:
    Label:
      en: DataDiskCategories
      zh-cn: 伸缩配置的数据盘类型
    Description:
      en: <p class="p">Note:</p> <ul class="ul"> <li class="li">This parameter is only valid when the instance contains at least one data disk.</li> </ul>
      zh-cn: <p class="p">注意：</p> <ul class="ul"> <li class="li">该参数仅在实例包含数据盘时有效。</li> </ul>
    Type: List
    AllowedValues:
      - cloud
      - cloud_efficiency
      - cloud_ssd
      - cloud_essd
      - cloud_auto
      - cloud_essd_entry
    Default: [ ]
  dataDiskSize:
    Label:
      en: DataDiskSize
      zh-cn: 伸缩配置的数据盘大小
    Description:
      en: <p class="p">Note:</p> <ul class="ul"> <li class="li">This parameter is only valid when the instance contains at least one data disk and DataDiskCategories is not empty.</li> </ul>
      zh-cn: <p class="p">注意：</p> <ul class="ul"> <li class="li">该参数仅在实例包含数据盘且DataDiskCategories不为空时有效。</li> </ul>
    Type: Number
    Default: 20
RamRole: '{{ OOSAssumeRole }}'
Tasks:
- Name: createImage
  Action: ACS::ECS::CreateImage
  Description:
    en: Create new image with the specified image name and instance ID
    zh-cn: 通过指定实例ID和镜像名称创建新的镜像
  Properties:
    imageName: '{{ targetImageName }}_on_{{ ACS::ExecutionId }}_at_{{ Acs::CurrentDate }}'
    instanceId: '{{ instanceId }}'
    tags: '{{tags}}'
  Outputs:
    imageId:
      ValueSelector: imageId
      Type: String
- Name: describeImages
  Action: ACS::ExecuteApi
  Description:
    en: Describe image
    zh-cn: 查询镜像信息
  Properties:
    Service: ecs
    API: DescribeImages
    Parameters:
      ImageId: '{{ createImage.imageId }}'
  Outputs:
    dataDisks:
      Type: Json
      ValueSelector: '.Images.Image[0].DiskDeviceMappings.DiskDeviceMapping|map( select(.Type == "data")|{"Device": (.Device),"SnapshotId":(.SnapshotId)})'
- Name: modifyScalingConfiguration
  Action: ACS::ExecuteAPI
  Description:
    en: Modify scaling configuration
    zh-cn: 修改伸缩配置
  Properties:
    Service: ESS
    API: ModifyScalingConfiguration
    Parameters:
      ScalingConfigurationId: '{{ ACS::TaskLoopItem }}'
      ImageId: '{{ createImage.imageId }}'
      DataDisk:
        Fn::If:
          - Fn::Not:
              Fn::Equals:
                - '{{ dataDiskCategories }}'
                - [ ]
          - Fn::Jq:
              - First
              - 'map({ Categories: {{ dataDiskCategories }}, Size: {{ dataDiskSize }}, Device, SnapshotId })'
              - '{{ describeImages.dataDisks }}'
          - Null
  Loop:
    Items: '{{ scalingConfigurationIds }}'
Outputs:
  imageId:
    Type: String
    Value: '{{ createImage.imageId }}'
