FormatVersion: OOS-2019-06-01
Description:
  en: Creates an ECS image and updates scaling configuration image ID.
  zh-cn: 创建一个新ECS镜像并更新伸缩配置中的镜像ID。
  name-en: ACS-ESS-CreateImageAndUpdateScalingConfiguration
  name-zh-cn: 创建一个新ECS镜像并更新弹性伸缩配置
  categories:
    - elastic_manage
Parameters:
  instanceId:
    Description:
      en: The id of ECS instance.
      zh-cn: ECS实例ID。
    Type: String
  targetImageName:
    Description:
      en: The name of new image.
      zh-cn: 新镜像的名称。
    Type: String
    MinLength: 1
    AllowedPattern: '[A-Za-z0-9\_\-\:\{\}\.]*'
    Default: CreateImage_from_{{instanceId}}
  scalingConfigurationIds:
    Description:
      en: The ID list of the scaling configuration to be modified.
      zh-cn: 待修改的伸缩配置IDs。
    Type: List
  tags:
    Description:
      en: The image tag.
      zh-cn: 镜像标签。
    Type: Json
    AssociationProperty: Tags
    AssociationPropertyMetadata:
      ShowSystem: false
    Default: []
  OOSAssumeRole:
    Description:
      en: The RAM role to be assumed by OOS.
      zh-cn: OOS扮演的RAM角色。
    Type: String
    Default: OOSServiceRole
RamRole: '{{ OOSAssumeRole }}'
Tasks:
- Name: createImage
  Action: ACS::ECS::CreateImage
  Description:
    en: Create new image with the specified image name and instance ID.
    zh-cn: 通过指定实例ID和镜像名称创建新的镜像。
  Properties:
    imageName: '{{ targetImageName }}_on_{{ ACS::ExecutionId }}_at_{{ Acs::CurrentDate }}'
    instanceId: '{{ instanceId }}'
    tags: '{{tags}}'
  Outputs:
    imageId:
      ValueSelector: imageId
      Type: String
- Name: modifyScalingConfiguration
  Action: ACS::ExecuteAPI
  Description:
    en: Modify scaling configuration.
    zh-cn: 修改伸缩配置。
  Properties:
    Service: ESS
    API: ModifyScalingConfiguration
    Parameters:
      ScalingConfigurationId: '{{ ACS::TaskLoopItem }}'
      ImageId: '{{ createImage.imageId }}'
  Loop:
    Items: '{{ scalingConfigurationIds }}'
Outputs:
  imageId:
    Type: String
    Value: '{{ createImage.imageId }}'
